---
- name: "Customizing Silverblue"
  hosts: localhost
  connection: local
  roles:
    #- role: "roles/rebase-install"
    - role: "roles/install-rpm"
    - role: "roles/install-flatpak" 
    - role: "roles/customize-settings" 
    #- role: "roles/toolbox-deploy" 
