---
- name: Install flatpaks
  community.general.flatpak:
    name:
      - app.drey.Warp
      - com.belmoussaoui.Authenticator
      - com.belmoussaoui.Decoder
      - com.brave.Browser
      - com.discordapp.Discord
      - com.github.huluti.Curtail
      - com.github.liferooter.textpieces
      - com.github.tchx84.Flatseal
      - com.mattjakeman.ExtensionManager
      - com.raggesilver.BlackBox
      - com.spotify.Client
      - com.valvesoftware.Steam
      - fr.romainvigier.MetadataCleaner
      - info.febvre.Komikku
      - io.github.seadve.Kooha
      - io.github.vikdevelop.SaveDesktop
      - md.obsidian.Obsidian
      - nl.g4d.Girens
      - nz.mega.MEGAsync
      - org.cryptomator.Cryptomator
      - org.freedesktop.Platform.ffmpeg-full/x86_64/22.08
      - org.freedesktop.Platform.openh264/x86_64/2.2.0
      - org.gimp.GIMP
      - org.gnome.Boxes
      - org.gnome.DejaDup
      - org.gnome.Podcasts
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gnome.gitlab.somas.Apostrophe
      - org.libreoffice.LibreOffice
      - org.mozilla.firefox
      - org.nickvision.tubeconverter
      - org.qbittorrent.qBittorrent
      - org.remmina.Remmina
      - org.zaproxy.ZAP

