---

- name: setup a new distrobox container
  shell: distrobox-create --image ubuntu:22.04 --name ubuntu-toolbox --yes -ap chezmoi

- name: deploy dot files
  shell: distrobox-enter --name ubuntu-toolbox -- chezmoi init --apply gaberob 

