---
- name: "load gnome shell keybindings"
  shell: dconf load / < "{{ role_path }}/files/keybindings.dconf"

- name: "load gnome tiling assistant keybindings"
  shell: dconf load / < "{{ role_path }}/files/tiling-assistant.dconf"


