---
- name: "load gnome shell keybindings"
  shell: dconf load / < "{{ role_path }}/files/keybindings.dconf"

- name: "load gnome tiling assistant keybindings"
  shell: dconf load / < "{{ role_path }}/files/tiling-assistant.dconf"

- name: "install icons"
  shell: git clone --depth 1 https://github.com/Frostbitten-jello/Skeuowaita.git ~/.local/share/icons/Skeuowaita

- name: 
  ansible.builtin.file:
    path: ~/Pictures/Wallpapers
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'

- name: get wallpapers
  ansible.builtin.git:
    repo: https://github.com/BitterSweetcandyshop/wallpapers.git
    dest: ~/Pictures/Wallpapers

- name: get themes
  ansible.builtin.git:
    repo: https://github.com/vinceliuice/Colloid-gtk-theme.git
    dest: ~/Colloid-gtk-theme 

- name: prefer dark mode
  shell: "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"


- name: install themes
  shell: "~/Colloid-gtk-theme/install.sh -t all --tweaks gruvbox"


- name: Recursively remove directory
  ansible.builtin.file:
    path: ~/.config/gtk-4.0
    state: absent

- name: copy gtk-4.0 config
  copy:
    src: ~/.themes/Colloid-Dark-Gruvbox/gtk-4.0
    dest: ~/.config/


- name: change theme
  shell: gsettings set org.gnome.desktop.interface gtk-theme "Colloid-Dark-Gruvbox"

- name: flatpak override
  shell: flatpak override --filesystem=$HOME/.themes
  become: yes

- name: "change icons"
  shell: gsettings set org.gnome.desktop.interface icon-theme 'Skeuowaita'

- name: Install bottle psutil package, dependency for setting bg
  ansible.builtin.pip:
    name: psutil

- name: Set GNOME Wallpaper
  become_user: me
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///var/home/gabe/Pictures/Wallpapers/unix_sorted/anime/jojo/VmmXijc-64388.png'"


- name: Set GNOME Wallpaper for dark mode
  become_user: me
  dconf: key="/org/gnome/desktop/background/picture-uri-dark" value="'file:///var/home/gabe/Pictures/Wallpapers/unix_sorted/anime/jojo/VmmXijc-64388.png'"
